
puts "Seeding started";
trainer1=Trainer.create(name: ' Tina Yogal', email: 'tina.yogalk@gmail.com', address: "Kings Landing,Nairobi");
trainer2=Trainer.create(name: 'Arya Fits', email: 'njorofits@gmail.com', address: "Winterfell,Nairobi")
trainer3=Trainer.create(name: 'Ramsey Lifts', email: 'ramseylifts@yahoo.com', address: "Dragon Stone,Nairobi")

tutorial1=Tutorial.create(name:  "5 Minute Guided Morning Meditation for Positive Energy" ,description:"Start your day with this 5 minute meditation for positive energy, refreshing your energy with visualization and positive affirmations. This 5 min meditation will help you cultivate gratitude, positivity and motivation for your day. Great for beginners and all levels." ,url: "https://youtu.be/j734gLbQFbU" ,trainer_id:trainer1.id)
tutorial2=Tutorial.create(name:  "Guided Meditation for Self Love " ,description:"Cultivate more self love, self confidence & self worth with this 12 minute guided meditation with positive affirmations. Download the audio to this self love meditation" ,url: "https://youtu.be/P-8ALcF8AGE" ,trainer_id:trainer1.id)
tutorial3=Tutorial.create(name:  "Guided Meditation for Anxiety & Stress " ,description:"Enjoy this 15 minute guided meditation for anxiety and stress. Relax and release tension from your mind and body. Use this meditation to cultivate gratitude, positive energy and peace. This meditation includes gentle neck stretches, full body relaxation, positive affirmations and visualization. Great for beginners and all levels. " ,url: "https://youtu.be/pxWOpGm4d7U" ,trainer_id:trainer2.id)
tutorial4=Tutorial.create(name:  "15 Minute Upper Body Dumbbell Workout [Strength Training]" ,description:"Tap in with us for a 15 minute upper body dumbbell workout that will help you build muscle (tone) and strength! This workout is designed for moderate to heavy resistance so you'll want to use a pair of dumbbells that are heavy enough to challenge yourself with each movement. If you're looking to build strength or muscle, we recommend going heavier in weight. For fat loss and muscular endurance, increase the temp with lighter weights. Each movement will finish with a 15 second iso metric hold to maximize those strength gains! Feel free to repeat this circuit for multiple sets for better results!  As always, try out the workout and let us know how you did! 🔥" ,url: "https://www.youtube.com/embed/NDOlPdyZLMg" ,trainer_id:trainer2.id)
tutorial5=Tutorial.create(name:  "10 MIN BEGINNER AB WORKOUT-No Equipment ",description:"If you have a hard time keeping up with my super intense ""10min Ab Workout 10min Sixpack Workout ) Everybody starts somewhere and my other workouts require suuuper strong core muscles. That's why I really wanted to create an ab workout, that is suitable for beginners - while still being super effective. " ,url: "https://www.youtube.com/embed/1f8yoFFdkcY" ,trainer_id:trainer2.id)
tutorial6=Tutorial.create(name:  "Intense Lower Abs Workout 🔥 Burn Lower Belly Fat 🤔" ,description:"Hot new lower abs workout for you! Here's a new favourite routine of mine with back to back abs exercise that's going to help you feel that burn! Enjoy working on those abs and do smash that like button and leave a comment!" ,url: "https://www.youtube.com/embed/JEEG0hBNk3E" ,trainer_id:trainer3.id)


    puts("Done seeding")